### ISSUE TITLE
Recommendation widget

### ISSUE THREAD

**Issue by Starrimus** [stacc-dasso/woocommerce-extension#30]
Estimated time: 15h
No detailed requirements available

**Comment by ilysion** [comment]
Going to use WooCommerce related products widget.
https://wordpress.stackexchange.com/questions/123436/how-to-customize-woocommerce-related-products
https://www.youtube.com/watch?v=-KtbgAcAQ4E
Almost all the WooCommerce themes support it, so it will be easy for the end user to change the appearance of the related products box.
