### ISSUE TITLE
Syncing store's inventory

### ISSUE THREAD

**Issue by Starrimus** [stacc-dasso/woocommerce-extension#36]
Estimated time: 15h
No detailed requirements available

**Comment by StiivoSiider** [comment]
Getting all of the store's products:
https://github.com/woocommerce/woocommerce/wiki/wc_get_products-and-WC_Product_Query

**Comment by StiivoSiider** [comment]
Get info from an Product object:
https://businessbloomer.com/woocommerce-easily-get-product-info-title-sku-desc-product-object/

This should work for different kinds of products, as it seems there isnt only WC_Product_Simple type product objects.
