### ISSUE TITLE
Implement an automatic system that could run set tasks daily

### ISSUE THREAD

**Issue by StiivoSiider** [stacc-dasso/woocommerce-extension#53]
Estimated effort: 10 hours

**Comment by StiivoSiider** [comment]
Ideas and info:
WP-Cron - https://developer.wordpress.org/plugins/cron/ (Not what we're looking for, only works on page load, so something needs to visit the page to always call the method at the same time)

PHP Thread - http://php.net/manual/en/thread.start.php (Maybe? No idea how feasible this might be, or easy to implement, or if it would even work or how resource intensive this might be)

**Comment by ilysion** [comment]
Some ideas how to visit pages to run cronJobs:
https://stackoverflow.com/questions/13259530/using-cron-jobs-to-visit-url?fbclid=IwAR3BQvHG-zGgWI4ubG8n0QU02Sgcdd1sMVcMdMzP23V0_bREyd6NwXApIW4

**Comment by StiivoSiider** [comment]
This will be up for discussion with the client at our next meeting.

**Comment by StiivoSiider** [comment]
The task is to create endpoints for sending logs and syncing inventory. STACC will call those endpoints.

**Comment by StiivoSiider** [comment]
Endpointid:
https://mingi.uus.domeen/recommender/recommendation/logs?h=#hash#&t=#unix_timestamp#

https://mingi.uus.domeen/recommender/recommendation/sync?h=#hash#&t=#unix_timestamp#
