### ISSUE TITLE
Check that logging is done properly everywhere.

### ISSUE THREAD

**Issue by ilysion** [stacc-dasso/woocommerce-extension#66]
Logging needs to be checked that everything that should be logged, is logged.

**Comment by Starrimus** [comment]
Estimated time: 2h/ea

**Comment by StiivoSiider** [comment]
Logging treshold needs to be changed to Warning or something similar.

**Comment by StiivoSiider** [comment]
For creating a treshold: https://docs.woocommerce.com/wc-apidocs/source-class-WC_Logger.html#86
